import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-landing',
  templateUrl: './landing.html',
})
export class LandingPage {
  constructor(private router: Router, private auth: AuthService) {}

  goToApp() {
    if (this.auth.isLoggedIn()) {
      this.router.navigate([this.auth.hasPreferences() ? '/dashboard' : '/preferences']);
    } else {
      this.router.navigate(['/auth']);
    }
  }

  features = [
    { icon: '🗺️', title: 'Smart Discovery', desc: 'Explore nearby parks, restaurants, clubs and more — filtered by category and distance.' },
    { icon: '🚗', title: 'Travel Modes', desc: 'Get accurate travel times for car, bike, or walking to every location.' },
    { icon: '🤖', title: 'AI Travel Planner', desc: 'Get personalized itineraries generated by AI based on your interests and preferences.' },
    { icon: '💡', title: 'Smart Matching', desc: 'Connect with like-minded people in your locality using our compatibility algorithm.' },
    { icon: '💬', title: 'Real-Time Chat', desc: 'Instantly connect and plan outings with your matches via built-in messaging.' },
    { icon: '🎯', title: 'Category Filters', desc: 'Narrow down places by type so you always find exactly what you\'re looking for.' },
  ];

  stats = [
    { value: '500+', label: 'Places Listed' },
    { value: '1K+', label: 'Active Users' },
    { value: '92%', label: 'Match Accuracy' },
    { value: '24/7', label: 'Always On' },
  ];
}
